
name: Daily Scraper

on:
  schedule:
    - cron: '30 3 * * *'  # 9 AM IST = 3:30 AM UTC
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.13.3
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper and save output
        run: |
          python main.py | tee scraper-log-$(date +'%Y-%m-%d').txt

      - name: Upload logs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: scraper-log
          path: scraper-log-*.txt
